### PR TITLE
Switch to Swashbuckle.AspNetCore v4.0

### PR DESCRIPTION
**Pull request by Leon99**

### CODE REVIEW

**Comment by Leon99** [comment]
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions.OperationFilter() was moved to another namespace in v4.0 (see https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/928), so Swashbuckle.AspNetCore.Filters has to be adjusted.

**Comment by mattfrear** [comment]
Hi Leon, thank you for attempting to fix this. It appears that the build failed, probably because Swashbuckle.AspNetCore is still in preview and thus can't be downloaded from NuGet. Where do you download it from?

Personally, I'm not in a hurry to support preview packages and would prefer to wait until it has been released before I upgrade.

**Comment by tomap** [comment]
Swashbuckle.AspNetCore 4 is out, could you update and merge this PR ?

Thank you

**Comment by mattfrear** [comment]
Sure, I will look at this when I get a chance over the next few days.

**Comment by mattfrear** [comment]
I've fixed this in another PR, so I'll close this one. Thanks for your contributions. I will release a NuGet package now.

**Comment by Leon99** [comment]
All good with v4.4.0, thanks @mattfrear

**Pull request closed without merging**
