### PR TITLE
upgrade openapi to 1.2.2 (#154)

### PR DESCRIPTION
**Pull request by CumpsD**
Fix for #154

### CODE REVIEW

**Comment by mattfrear** [comment]
Hmm, this looks like a bit of a mess. I guess the OpenApi developers thought that adding a new optional parameter is not a breaking change. I probably would have made the same mistake.

I've pulled down your fix locally and it's not working for me - I get the same `MissingMethodException` when I try to run the test API projects 🤷‍♂️

**Comment by CumpsD** [comment]
Yeah, optional parameters are a bit tricky :(

Hmm, do you get it after recompiling too? I'll double check, but after recompiling it binds to the new 2 parameter ctor normally.

Something for this evening :)

**Comment by mattfrear** [comment]
I didn't spend too long on it but yes I pulled down your changes, did a Build -> Clean, and still hit the exception.

**Comment by CumpsD** [comment]
Strange, I'll investigate some more

image

**Comment by CumpsD** [comment]
Ah but it seems now it is being thrown from `Swashbuckle.AspNetCore.SwaggerGen` and not this repo :)

```
System.MissingMethodException: Method not found: 'Void Microsoft.OpenApi.Any.OpenApiString..ctor(System.String)'.
   at Swashbuckle.AspNetCore.SwaggerGen.OpenApiAnyFactory.CreateFor(OpenApiSchema schema, Object value)
   at Swashbuckle.AspNetCore.SwaggerGen.JsonEnumHandler.<>c__DisplayClass4_0.<CreateSchema>b__1(Object value)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Swashbuckle.AspNetCore.SwaggerGen.JsonEnumHandler.CreateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGeneratorBase.<>c__DisplayClass4_1.<GenerateSchema>b__0()
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.GetOrAdd(Type type, String schemaId, Func`1 factoryMethod)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGeneratorBase.CreateReferenceSchema(Type type, SchemaRepository schemaRepository, Func`1 factoryMethod)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGeneratorBase.GenerateSchema(Type type, SchemaRepository schemaRepository)   at Swashbuckle.AspNetCore.SwaggerGen.JsonObjectHandler.CreatePropertySchema(PropertyInfo property, IEnumerable`1 customAttributes, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.JsonObjectHandler.CreateObjectSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.JsonObjectHandler.CreateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGeneratorBase.<>c__DisplayClass4_1.<GenerateSchema>b__0()
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.GetOrAdd(Type type, String schemaId, Func`1 factoryMethod)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGeneratorBase.CreateReferenceSchema(Type type, SchemaRepository schemaRepository, Func`1 factoryMethod)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGeneratorBase.GenerateSchema(Type type, SchemaRepository schemaRepository)   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreateResponseMediaType(ModelMetadata modelMetadata, SchemaRepository schemaRespository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.<>c__DisplayClass18_0.<GenerateResponse>b__2(String contentType)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateResponse(ApiDescription apiDescription, SchemaRepository schemaRepository, String statusCode, ApiResponseType apiResponseType)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateResponses(ApiDescription apiDescription, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Let me check, this has still a dep on 5.0.0 and they are at 5.5.0

**Comment by CumpsD** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1717

**Comment by CumpsD** [comment]
I've updated the PR to pin on 1.1.4 until they fix it. It runs now :)

**Comment by CumpsD** [comment]
Wait a bit with merging @mattfrear, I'm fixing it at the source: https://github.com/microsoft/OpenAPI.NET/pull/492

**Comment by CumpsD** [comment]
@mattfrear ready! MS released 1.2.2 with all the breaking changes solved.

**Comment by mattfrear** [comment]
Nice work David, thanks!

I've released it https://www.nuget.org/packages/Swashbuckle.AspNetCore.Filters/5.1.2

**Pull request merged**
