### PR TITLE
Adding support for minimal APIs in the OperationFilterContextExtensions

### PR DESCRIPTION
**Pull request by dotdiego**
Hey,

This is my resolution on #189 
I've added the same unit tests as the ones regarding to ControllerAction but for minimal APIs

Can you tell me what you think of it ?

Regards,

### CODE REVIEW

**Comment by Didev1** [comment]
@mattfrear build seems to be failing because there are no .net 6 sdk on the pipeline.

**Comment by mattfrear** [comment]
Hi Diego

Thanks for the PR. I haven't had a chance to look at it or understand the problem either, but I will try to do it some time in the next week.

Matt

**Comment by dotdiego** [comment]
Thanks for the quick reply.

I'll update my tests in the next days too.

They feel more like integration tests than unit tests with the creation of the WebApplicationFactory.
I'll rewrite them with only mocking an Endpoint and not the whole asp.net pipeline.

Regards,

**Comment by mattfrear** [comment]
Hi diego
Thanks for the PR. 
Your changes to OperationFilterContextExtensions work ✔️ 
However, not all of the filters are using your changes, there were still calls to `context.MethodInfo.GetCustomAttributes` in other filters ❌ 
When I try to test these changes with a minimal web api solution, it doesn't work but for a different reason ❌ 
```
Swashbuckle.AspNetCore.Filters.MvcOutputFormatter+FormatterNotFoundException: OutputFormatter not found for 'application/json; charset=utf-8'
   at Swashbuckle.AspNetCore.Filters.MvcOutputFormatter.Serialize[T](T value, MediaTypeHeaderValue contentType) in
```
Just wondering - did you try and test your changes locally?

You've added tests to `AppendAuthorizeToSummaryOperationFilterTests` which is good, however I don't think we need to duplicate every test. I've removed most of the duplicate tests and just left in a couple.
Most people who use this NuGet use it for Request and Response examples, so there probably would have been more value in adding tests for those use cases.

I have done some changes to your branch, but I don't know how to push them so that they are included in your PR. I have pushed my changes to a new branch, called `dotdiego`.

It still needs some work - if you set the new test/WebApi6.0-Swashbuckle6 project to be the Startup project and run it, you'll see the above exception.

**Comment by dotdiego** [comment]
I'll check that more in depth tomorrow, i've added you as a contributor on my forked repo if you want to add commits to the PR (i'm not really knowledgeable about all that yet).
Yes i've tested locally that it does work, but i'm only using the SecurityRequirements and AppendAuthorizeToSummary filters.
I've seen on the README of the project that Request/Response examples filters were not to be used anymore.

I guessed that they were on the way to become obsolete and didn't thought it would be the most used filters. 
I will try to find a way to replace those calls too.

**Comment by mattfrear** [comment]
Cool, I've pushed my changes to your branch and deleted the dotdiego branch from here.

> I've seen on the README of the project that Request/Response examples filters were not to be used anymore.

Yeah, I'm trying to move users away from using request and response examples filters so that I don't have to support them, and because Swashbuckle.AspNetCore now supports it out of the box. Swashbuckle.AspNetCore didn't use to support request and response examples, and my filters used to be the only way, so there are a lot of users that still use my filters. Probably 90% of my users use those.

**Comment by dotdiego** [comment]
Ok it seems normal that it doesn't work for MvcOutputFormatter (since Minimal API is not part of MVC), because there are no ```IOptions<MvcOptions>```

Endpoints are containing metadatas like ```AcceptsMetadata``` (internal class). Those metadatas should be the equivalent of the OutputFormatters. I don't know exactly how to replace the ```MvcOutputFormatter``` yet in the code for endpoints.

**Comment by mattfrear** [comment]
> Minimal APIs do not support Content Negotiation according to : https://benfoster.io/blog/mvc-to-minimal-apis-aspnet-6/
> 
> > One thing I spotted when digging into the source is that ObjectResult, the base class for the IResult implementations that serialize objects, only supports serializing JSON. I’m told this was by design since most developers rarely need to support other media types. If you need to support content negotiation you’ll likely need to build your own implementation of IResult.

OK, so maybe we can just default to a JSON example then, using System.Text.Json. I have added code to do this.

**Pull request merged**
