### PR TITLE
Create Abstractions Package

### PR DESCRIPTION
**Pull request by buvinghausen**
@mattfrear let me know if you need any changes.  I hoisted most of your csproj elements to the Directory.Build.props file so you can change the values once and it applies to both packages.

Thanks

### CODE REVIEW

**Comment by mattfrear** [comment]
Cool, I didn't know about `Directory.Build.props`. 

This looks good. I'm just wondering, when I release this, will Swashbuckle.Asp.NetCore.Filters have a dependency on the .Abstractions package? Or will it be included automatically?

And as far as my versioning goes, is this a minor version bump or a major one? Considering that in your last PR, we removed the dependency on Swashbuckle.AspNetCore... I'm thinking that could be a breaking change, what do you think?

**Comment by mattfrear** [comment]
Thanks for the `Microsoft.SourceLink.GitHub` package reference. I didn't know about that either! Debugging NuGet packages has been a pain forever, I remember blogging a hack a few years ago.

**Comment by mattfrear** [comment]
OK so I decided to release this and a breaking change together so I did a major version bump.

**Comment by mattfrear** [comment]
> This looks good. I'm just wondering, when I release this, will Swashbuckle.Asp.NetCore.Filters have a dependency on the .Abstractions package? Or will it be included automatically?

Yes, it does, and now I have to ensure that I release the .Abstractions package every time I do a version bump, which isn't ideal:
```
Error	NU1102	Unable to find package Swashbuckle.AspNetCore.Filters.Abstractions with version (>= 7.0.2)
  - Found 1 version(s) in api.nuget.org [ Nearest version: 7.0.0 ]
```

**Comment by buvinghausen** [comment]
@mattfrear yeah there are two schools of thought.  One is publish a new version of the entire stack every time so there is no confusion as to which is which or you can decouple the deployment of them and version them independently.

Given the static nature of the abstractions package the latter may be the correct path for you. I didn't look at your deployment setup so I just set it up to push both packages every time.  It should be easy enough to have your main repository pull the abstractions package off nuget rather than the project reference and then you can version them separately.

**Comment by mattfrear** [comment]
Hi @buvinghausen yeah given that the abstraction project will never change, I'd prefer to not have to republish it every time.

**Comment by buvinghausen** [comment]
@mattfrear totally get it.  FYI I just pulled the latest bits into the project and everything works like I expected.  Thank you for dropping the dependency on Newtonsoft as well!

**Pull request merged**
