### PR TITLE
Added support for text/csv in response examples

### PR DESCRIPTION
**Pull request by icnocop**

### CODE REVIEW

**Comment by mattfrear** [comment]
Nice, looks good. I'll test it locally when I get a chance.

**Comment by mattfrear** [comment]
Could you please add CSV support to one of the included test projects' endpoints? So that I can spin it up and see it working.
I think I've only built an API which returned CSV once and it was probably on .NET Framework.

**Comment by icnocop** [comment]
> Could you please add CSV support to one of the included test projects' endpoints? So that I can spin it up and see it working. 

Done.

Thank you.

**Comment by mattfrear** [comment]
Thanks for the PR.

Released https://www.nuget.org/packages/Swashbuckle.AspNetCore.Filters/7.0.4

**Pull request merged**
