### PR TITLE
Make OpenApiRawString public

### PR DESCRIPTION
**Pull request by WillGunn**
I'm in a position where I need to access the value of the OpenApiRawString from a document filter, but am unable to do so because OpenApiRawString is internal and the operation example property is of type IOpenApiAny which does not have a value property.

If you are wondering why, I need to modify the example of an operation depending on what spec I'm currently generating.  So for some specs it is using the full example, and others a partially stripped down example.

### CODE REVIEW

**Comment by mattfrear** [comment]
Hi Will

We need to look into this further... the `OpenApiRawString` was introduced by someone else, and at the time it was a workaround because no such class was offered in Microsoft.OpenApi. But there might well be a class which we can use in the Microsoft.OpenApi namespace instead (by now). In which case we could remove the OpenApiRawString from this project and use that alternative class.

**Comment by WillGunn** [comment]
So it looks like you first added OpenApiRawString June of last year, the OpenApiString now has an explicit constructor parameter which looks like it does something similar regarding encoding:
https://github.com/microsoft/OpenAPI.NET/blob/vnext/src/Microsoft.OpenApi/Any/OpenApiString.cs
The change was first introduced in Nov of last year in this commit:
https://github.com/microsoft/OpenAPI.NET/commit/2c7663a0c709a71b7126097fab97e7d190024fdf#diff-e3bc96ab286ce70b6be74a1f9a23ca974df29656a61482fa928e5d847bf5a88d

So we may be able to use this in place of the custom one.

**Comment by WillGunn** [comment]
No luck, it still double encodes it, the SetsResponseExamples_CorrectlyFormatsJsonExample test fails because the formatted example is:
`"\"{\\r\\n  \\\"id\\\": 123,\\r\\n  \\\"title\\\": 1,\\r\\n  \\\"first\\\": \\\"John\\\",\\r\\n  \\\"last\\\": \\\"Doe\\\",\\r\\n  \\\"income\\\": null\\r\\n}\""`
instead of
`"{\r\n  \"id\": 123,\r\n  \"title\": 1,\r\n  \"first\": \"John\",\r\n  \"last\": \"Doe\",\r\n  \"income\": null\r\n}"`

**Comment by WillGunn** [comment]
I dug into the OpenApi code, and it seems the writer in the base OpenApiPrimitive doesn't take into account the Explicit parameter, I opened an issue with them: https://github.com/microsoft/OpenAPI.NET/issues/527

**Comment by mattfrear** [comment]
Nice digging Will!

I'm sorry you had to go down a rabbit hole when what you want to do is relatively simple. 

I don't think it's a good idea for me to make OpenApiRawString public because once it is public I won't be able to remove it (without it being a breaking change). Let's see what the OpenApi guys say.

**Comment by WillGunn** [comment]
@mattfrear I reached out to one of the maintainers on twitter as he said to do so in a different issue, https://twitter.com/darrel_miller/status/1321139170543345664

I wrote a PR that should allow this functionality: https://github.com/microsoft/OpenAPI.NET/pull/528

**Comment by darrelmiller** [comment]
@WillGunn  Thanks for the PR.  I will review ASAP.

**Comment by WillGunn** [comment]
@mattfrear the PR was merged the other day: https://github.com/microsoft/OpenAPI.NET/pull/528, so in theory it should become available on the next release whenever that is.

**Comment by WillGunn** [comment]
@mattfrear so my MS pr got merged in https://github.com/microsoft/OpenAPI.NET/pull/528 and I think its in OpenApi.NET 1.2.4

**Comment by darrelmiller** [comment]
@WillGunn There never actually was a 1.2.4 release.  Some magical GitHub action created that release.  The 1.2.4 fixes were rolled into the 1.3.0-preview release https://github.com/microsoft/OpenAPI.NET/releases/tag/1.3.0-preview

**Comment by mattfrear** [comment]
I see OpenAPI.NET 1.3.1 was released last month.
I have consumed that package and now use OpenApiString with isRawString parameter, and so have deleted `OpenApiRawString`.

**Comment by mattfrear** [comment]
Released https://www.nuget.org/packages/Swashbuckle.AspNetCore.Filters/7.0.3

**Pull request closed without merging**
