### PR TITLE
Update Swashbuckle to 3.0

### PR DESCRIPTION
**Pull request by 0x53A**
fixes https://github.com/mattfrear/Swashbuckle.AspNetCore.Examples/issues/46

### CODE REVIEW

**Comment by mattfrear** [comment]
Thank you for the PR. I will review it tomorrow. If it is a breaking change, which it sounds like it is, then we will need to upgrade the major version number.

**Comment by mattfrear** [comment]
Ah oops, looks like I merged this PR too quickly - the unit tests fail on my machine 👎

**Comment by 0x53A** [comment]
sorry, I had issues with running the tests (no netcore1.x installed on my machine).

I took a look again and I think the tests need to be slightly restructured.

Upstream swashbuckle now doesn't directly expose the controller, but instead uses the MethodInfo. The only way to get the controller (AFAIK) is to use ``MethodInfo.DeclaringType``.

So the split between actions (``FakeActions``) and controllers (``FakeControllers``) doesn't work anymore (I think).

**Comment by mattfrear** [comment]
Yeah, I'm trying to figure it out at the moment, which is interrupting my Wimbledon tennis viewing.

**Comment by 0x53A** [comment]
I made the tests green in https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/pull/48.

This doesn't really match with your previous test scheme, so I don't think it should be merged as-is, but maybre it helps as a pointer.

**Pull request merged**
