### PR TITLE
Add Table of Contents

### PR DESCRIPTION
**Pull request by spottedmahn**
related to https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/issues/58

### CODE REVIEW

**Comment by spottedmahn** [comment]
[Working example](https://github.com/spottedmahn/Swashbuckle.AspNetCore.Filters/tree/toc)

**Comment by spottedmahn** [comment]
toc on swashbuckle filters

**Comment by mattfrear** [comment]
Thanks for the PR, and for the animated GIF 👌

**Comment by spottedmahn** [comment]
thanks for the great library!!

**Pull request merged**
